import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { business, routes } from '../config/business';
import { media } from '../config/media';
import { generalEnquiryLink } from '../lib/whatsapp';
import { listPublicReviews, type Review } from '../services/reviewService';
import Reveal from '../components/Reveal';
import SeoHead from '../components/SeoHead';

export default function Reviews(){
 const [reviews,setReviews]=useState<Review[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;listPublicReviews().then(items=>{if(live)setReviews(items)}).catch(()=>{if(live)setReviews([])}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
 return <main className="pt-16 md:pt-20 pb-mobile-nav min-h-screen">
  <SeoHead title={`Customer Looks & Reviews — ${business.name}`} description="Verified customer reviews and looks for Duchess Hairline in Port Harcourt."/>
  <section className="relative h-[48vh] md:h-[58vh] min-h-[340px] flex items-end overflow-hidden"><img src={media.editorialAlt} alt="Duchess Hairline customer styling" className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/35 to-black/10"/><div className="relative z-10 w-full max-w-[1440px] mx-auto px-4 md:px-8 lg:px-12 pb-14 md:pb-20"><p className="label-text text-white/50 mb-4">Community</p><h1 className="hero-heading text-white leading-[0.92]">REAL PEOPLE.<br/>REAL LOOKS.</h1></div></section>
  <section className="bg-cream"><div className="max-w-[1440px] mx-auto px-4 md:px-8 lg:px-12"><dl className="grid grid-cols-2 divide-x divide-beige/50 py-10 md:py-14"><div className="text-center"><dd className="font-display text-3xl md:text-5xl text-deep-black font-light">{business.social.tiktok.followers}</dd><dt className="label-text text-charcoal/40 mt-2">TikTok Followers</dt></div><div className="text-center"><dd className="font-display text-3xl md:text-5xl text-deep-black font-light">{business.social.tiktok.likes}</dd><dt className="label-text text-charcoal/40 mt-2">TikTok Likes</dt></div></dl></div></section>
  <section className="py-16 md:py-24"><div className="max-w-[1200px] mx-auto px-4 md:px-8"><Reveal className="text-center max-w-2xl mx-auto mb-12 md:mb-16"><p className="label-text text-charcoal/50 mb-4">Testimonials</p><h2 className="section-heading text-deep-black mb-5">CUSTOMER REVIEWS</h2><p className="text-sm text-charcoal/60 leading-relaxed">Reviews shown here are approved customer submissions. The admin can moderate them before they become public.</p></Reveal>
   {loading?<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{[1,2,3].map(n=><div key={n} className="h-48 rounded-2xl bg-cream animate-pulse"/> )}</div>:reviews.length===0?<div className="rounded-3xl border border-dashed border-beige p-10 md:p-16 text-center"><p className="label-text text-beige mb-3">No reviews published yet</p><h3 className="font-display text-3xl mb-4">Your story can be next.</h3><p className="text-sm text-charcoal/55 max-w-md mx-auto leading-6">If you have purchased from Duchess Hairline, share your experience with the business. Approved reviews will appear here.</p><a href={generalEnquiryLink()} target="_blank" rel="noopener noreferrer" className="btn-whatsapp mt-7">Share on WhatsApp</a></div>:<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{reviews.map((r,i)=><Reveal key={r.id} delay={(i%3)*.05}><article className="h-full rounded-2xl border border-beige/25 bg-white p-7 md:p-8 flex flex-col">{r.image&&<img src={r.image} alt={`${r.name||'Customer'} customer look`} className="w-full aspect-[4/3] object-cover rounded-xl mb-6" loading="lazy"/>}<div className="text-[#b8956a] tracking-widest text-sm" aria-label="Customer review">★★★★★</div><p className="mt-4 text-sm leading-7 text-charcoal/70">“{r.text||'Customer review'}”</p><div className="mt-auto pt-6"><p className="font-medium text-deep-black">{r.name||'Customer'}</p>{r.productName&&<p className="text-xs text-charcoal/40 mt-1">{r.productName}</p>}</div></article></Reveal>)}</div>}
  </div></section>
  <section className="py-16 md:py-24 bg-cream/30"><div className="max-w-[1440px] mx-auto px-4 md:px-8 lg:px-12"><Reveal className="text-center mb-12 md:mb-16"><p className="label-text text-charcoal/50 mb-3">Gallery</p><h2 className="section-heading text-deep-black mb-4">CUSTOMER LOOKS</h2><p className="text-sm text-charcoal/50 max-w-md mx-auto">Customer photos can be added through the review system once permission to publish has been received.</p></Reveal>{reviews.filter(r=>r.image).length===0?<div className="rounded-3xl border border-dashed border-beige p-10 text-center text-sm text-charcoal/40">Customer photos will appear here when approved reviews include images.</div>:<div className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-4">{reviews.filter(r=>r.image).slice(0,8).map((r,i)=><Reveal key={r.id} delay={(i%4)*.05}><img src={r.image} alt={`${r.name||'Customer'} look`} className="w-full aspect-[3/4] object-cover rounded-xl" loading="lazy"/></Reveal>)}</div>}</div></section>
  <section className="relative overflow-hidden bg-deep-black"><div className="grid grid-cols-1 lg:grid-cols-2 min-h-[440px]"><div className="flex items-center px-6 md:px-12 lg:px-16 py-16 lg:py-0 order-2 lg:order-1"><Reveal><p className="label-text text-white/30 mb-3">Social</p><h2 className="font-display text-3xl md:text-5xl text-white font-light leading-[1.05] mb-5">SEE THE WIGS<br/>IN MOTION</h2><p className="text-white/40 text-sm leading-relaxed mb-8 max-w-sm">Our TikTok is where customers can see styles in motion and discover new looks.</p><a href={business.social.tiktok.url} target="_blank" rel="noopener noreferrer" className="btn-white">Follow {business.social.tiktok.handle}</a></Reveal></div><div className="relative overflow-hidden order-1 lg:order-2 min-h-[320px]"><img src={media.editorialPortrait} alt="Duchess Hairline on TikTok" loading="lazy" className="w-full h-full object-cover"/></div></div></section>
  <section className="py-16 md:py-24 lg:py-32"><div className="max-w-[1440px] mx-auto px-4 md:px-8 lg:px-12 text-center"><Reveal><h2 className="font-display text-3xl md:text-5xl text-deep-black font-light leading-[1.05] mb-6">SHARE YOUR LOOK.<br/>BE FEATURED.</h2><p className="text-sm text-charcoal/60 max-w-md mx-auto mb-10 leading-relaxed">Send us a photo on WhatsApp or tag us on TikTok. We ask permission before publishing anything.</p><div className="flex flex-wrap justify-center gap-3"><a href={generalEnquiryLink()} target="_blank" rel="noopener noreferrer" className="btn-whatsapp">Share on WhatsApp</a><Link to={routes.collection} className="btn-outline">View Collection</Link></div></Reveal></div></section>
 </main>;
}
